### ISSUE TITLE
Unable to updated form 1.2.23 to 1.2.25

### ISSUE THREAD

**Issue by bartoszek** [otwarty-wykop-mobilny/wykop-android#348]
Trying to update app using the APK file form the latest release section I'm getting an error popups stating: App not installed ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
![Screenshot_20220928-091240_Package installer.jpg](https://user-images.githubusercontent.com/1213348/192713539-1465854b-898d-4163-9fee-095dfd2d1af5.jpg)
Are there any special routine to update the app when the play store version was previously installed?

**Comment by mateuszkwiecinski** [comment]
>Are there any special routine to update the app when the play store version was previously installed?

Actually there is, you have completely uninstall old version. Previously apk signing was managed by Google Play Store, where I didn't really have access to the signing key. APKs attached to github releases are signed with my own key, hence the incompatibility. 
If you remove the previously installed app from your device you should be able to install the latest version from Github :)
